export type HookahAroma = { id: string; name: string; color: string; nameKey?: string }
export type HookahBrand = { id: string; name: string; desc: string; price: string; icon: string; aromas: HookahAroma[] }

export const HOOKAH_BRANDS: HookahBrand[] = [
  {
    id: 'revoshi',
    name: 'Revoshi',
    desc: 'Premium Tobacco',
    price: '₺500',
    icon: '◎',
    aromas: [
      { id: 'r-double-apple',      name: 'Double Apple',       color: '#ef4444' },
      { id: 'r-uzum',              name: 'Üzüm',               color: '#a855f7',  nameKey: 'hookah.aromas.uzum' },
      { id: 'r-uzum-nane',         name: 'Üzüm Nane',          color: '#818cf8',  nameKey: 'hookah.aromas.uzum_nane' },
      { id: 'r-biskuvi',           name: 'Bisküvi',             color: '#d4a574',  nameKey: 'hookah.aromas.biskuvi' },
      { id: 'r-portakal',          name: 'Portakal',            color: '#f97316',  nameKey: 'hookah.aromas.portakal' },
      { id: 'r-limon',             name: 'Limon',               color: '#facc15',  nameKey: 'hookah.aromas.limon' },
      { id: 'r-kavun',             name: 'Kavun',               color: '#fbbf24',  nameKey: 'hookah.aromas.kavun' },
      { id: 'r-yaban-bogurtleni',  name: 'Yaban Böğürtleni',   color: '#9333ea',  nameKey: 'hookah.aromas.yaban_bogurtleni' },
      { id: 'r-cilek',             name: 'Çilek',               color: '#ec4899',  nameKey: 'hookah.aromas.cilek' },
      { id: 'r-ananas',            name: 'Ananas',              color: '#eab308',  nameKey: 'hookah.aromas.ananas' },
      { id: 'r-cikolata-nane',     name: 'Çikolata Nane',       color: '#a16207',  nameKey: 'hookah.aromas.cikolata_nane' },
      { id: 'r-eskimo-karpuz',     name: 'Eskimo Karpuz',       color: '#f87171' },
      { id: 'r-nane',              name: 'Nane',                color: '#34d399',  nameKey: 'hookah.aromas.nane' },
      { id: 'r-pismis-seftali',    name: 'Pişmiş Şeftali',      color: '#fb923c',  nameKey: 'hookah.aromas.pismis_seftali' },
      { id: 'r-eskimo-kola',       name: 'Eskimo Kola',         color: '#6b7280' },
      { id: 'r-mamdelas',          name: 'Mamdelas 27',         color: '#84cc16' },
      { id: 'r-te-extrano',        name: 'Te Extrano Fidel',    color: '#22d3ee' },
      { id: 'r-mastic',            name: 'Mastic',              color: '#fef9c3' },
      { id: 'r-pancho-villa',      name: 'Pancho Villa',        color: '#f59e0b' },
      { id: 'r-strawberry-banana', name: 'Strawberry Banana',   color: '#f472b6' },
      { id: 'r-peach-marmalade',   name: 'Peach Marmalade',     color: '#fb923c' },
      { id: 'r-fosbury',           name: 'Fosbury',             color: '#06b6d4' },
      { id: 'r-kiwi-mango',        name: 'Kiwi Mango',          color: '#4ade80' },
      { id: 'r-domingo',           name: 'Domingo',             color: '#f43f5e' },
      { id: 'r-vanilya-melonade',  name: 'Vanilya Melonade',    color: '#fde68a',  nameKey: 'hookah.aromas.vanilya_melonade' },
      { id: 'r-cinnamon',          name: 'Cinnamon',            color: '#92400e' },
      { id: 'r-choco-nut',         name: 'Choco Nut',           color: '#78350f' },
    ],
  },
  {
    id: 'hookah_special',
    name: 'Hookah Special',
    desc: 'Ice Cream Series',
    price: '₺650',
    icon: '❋',
    aromas: [
      { id: 'hs-blueberry-ice',   name: 'Blueberry Ice Cream',   color: '#818cf8' },
      { id: 'hs-strawberry-ice',  name: 'Strawberry Ice Cream',  color: '#f472b6' },
      { id: 'hs-chocolate-ice',   name: 'Chocolate Ice Cream',   color: '#78350f' },
      { id: 'hs-peach-ice',       name: 'Peach Ice Cream',       color: '#fb923c' },
      { id: 'hs-hookah-special',  name: 'Hookah Special',        color: '#fbbf24' },
    ],
  },
  {
    id: 'al_fakher',
    name: 'Al Fakher',
    desc: 'Classic Blend',
    price: '₺500',
    icon: '⬡',
    aromas: [
      { id: 'af-double-apple',   name: 'Double Apple',   color: '#ef4444' },
      { id: 'af-uzum',           name: 'Üzüm',           color: '#a855f7', nameKey: 'hookah.aromas.uzum' },
      { id: 'af-yaban-mersini',  name: 'Yaban Mersini',  color: '#6366f1', nameKey: 'hookah.aromas.yaban_mersini' },
    ],
  },
  {
    id: 'nakhla',
    name: 'Nakhla',
    desc: 'Dark Leaf',
    price: '₺600',
    icon: '◆',
    aromas: [
      { id: 'n-seftali',    name: 'Şeftali',    color: '#fb923c', nameKey: 'hookah.aromas.seftali' },
      { id: 'n-cappuccino', name: 'Cappuccino', color: '#92400e' },
    ],
  },
  {
    id: 'adalya',
    name: 'Adalya',
    desc: 'Special Edition',
    price: '₺500',
    icon: '✦',
    aromas: [
      { id: 'a-love-66',       name: 'Love 66',       color: '#f43f5e' },
      { id: 'a-lady-killer',   name: 'Lady Killer',   color: '#e879f9' },
      { id: 'a-ice-bonbon',    name: 'Ice Bonbon',    color: '#7dd3fc' },
      { id: 'a-berlin-night',  name: 'Berlin Night',  color: '#6366f1' },
      { id: 'a-moscow-night',  name: 'Moskow Night',  color: '#4f46e5' },
      { id: 'a-baku-night',    name: 'Bakü Night',    color: '#7c3aed' },
      { id: 'a-izmir-romantik',name: 'İzmir Romantik',color: '#e879f9' },
      { id: 'a-mia-mor',       name: 'Mia Mor',       color: '#c026d3' },
    ],
  },
]
