export const FOOD_MENU = [
  {
    id: 'breakfast',
    category: 'Breakfast & Sandwiches',
    items: [
      { key: 'fried_eggs', name: 'Sahanda Yumurta', desc: '', price: '₺240', calories: '210' },
      { key: 'kavurma_eggs', name: 'Kavurmalı Yumurta', desc: '', price: '₺350', calories: '420' },
      { key: 'sucuk_eggs', name: 'Sucuklu Yumurta', desc: '', price: '₺280', calories: '390' },
      { key: 'menemen', name: 'Menemen', desc: '', price: '₺280', calories: '180' },
      { key: 'omelet', name: 'Omlet', desc: '', price: '₺290', calories: '190' },
      { key: 'cheese_plate', name: 'Peynir Tabağı', desc: '', price: '₺290', calories: '340' },
      { key: 'soup_of_day', name: 'Günün Çorbası', desc: '', price: '₺260', calories: '130-160' },
    ],
  },
  {
    id: 'toasts',
    category: 'Toasts',
    items: [
      { key: 'mixed_toast', name: 'Karışık Tost', desc: 'Dana sucuk, dana salam, dana sosis, mozerella, patates', price: '₺350', calories: '520' },
      { key: 'sucuk_toast', name: 'Sucuklu Tost', desc: 'Dana sucuk, mozerella, patates', price: '₺320', calories: '460' },
      { key: 'boritos_wrap', name: 'Boritos', desc: 'Dana sucuk, cheddar peyniri, mozerella, özel sos dürüm hali', price: '₺380', calories: '580' },
      { key: 'salami_toast', name: 'Salamlı Tost', desc: 'Dana salam, mozerella, patates', price: '₺340', calories: '430' },
      { key: 'kasarli_tost', name: 'Kaşarlı Tost', desc: '', price: '₺320', calories: '' },
      { key: 'hookah_kumru', name: 'Hookah Special Kumru', desc: 'Dana sucuk, dana sosis, dana salam, eritme kaşar peyniri', price: '₺370', calories: '680' },
      { key: 'build_your_toast', name: 'Kendi Tostunu Kendin Yarat', desc: '', price: '', calories: '' },
    ],
  },
  {
    id: 'boritos',
    category: 'Boritos',
    items: [
      { key: 'bonfile_boritos', name: 'Bonfile Boritos', desc: '120 gr bonfile, domates, marul, özel sos, cheddar peyniri, patates kızartması', price: '₺480', calories: '620' },
      { key: 'chicken_boritos', name: 'Tavuk Boritos', desc: '120 gr özel hazırlanmış tavuk, domates, marul, turşu ve özel sos, patates kızartması', price: '₺420', calories: '580' },
      { key: 'kofte_boritos', name: 'Köfte Boritos', desc: 'Special köfte, domates, marul, cheddar, özel sos ve patates kızartması', price: '₺450', calories: '640' },
      { key: 'quesadilla', name: 'Quesadilla', desc: '120 gr soslu tavuk, mozerella, cheddar ve patates kızartması', price: '₺440', calories: '690' },
    ],
  },
  {
    id: 'salads',
    category: 'Salads',
    items: [
      { key: 'chicken_salad', name: 'Tavuk Salata', desc: '', price: '₺420', calories: '380' },
      { key: 'steak_salad', name: 'Biftek Salata', desc: '', price: '₺450', calories: '440' },
      { key: 'mediterranean_salad', name: 'Akdeniz Salata', desc: '', price: '₺390', calories: '260' },
    ],
  },
  {
    id: 'burgers',
    category: 'Burgers',
    items: [
      { key: 'burger_classic', name: 'Hamburger Classic', desc: 'Dana köfte 120 gr, domates, turşu, marul, patates kızartması ile servis edilir', price: '₺450', calories: '780' },
      { key: 'cheeseburger', name: 'Cheeseburger', desc: 'Dana köfte 120 gr, domates, turşu, marul, cheddar peyniri, patates kızartması ile servis edilir', price: '₺470', calories: '870' },
      { key: 'triple_mini_burger', name: 'Üçlü Mini Burger', desc: 'Üç adet farklı tavuk, köfte, et köfte ile hazırlanan lezzet minileri, patates kızartması ile servis edilir', price: '₺420', calories: '890' },
      { key: 'chicken_burger', name: 'Tavuk Burger', desc: 'Çıtır tavuklarımız ile hazırlanan classic burger, patates kızartması ile servis edilir', price: '₺420', calories: '810' },
      { key: 'bonfile_burger', name: 'Yaprak Bonfile Burger', desc: 'Bonfile dilimlerinin mantar, kırmızı biber ve cheddar peyniri ile buluşması, patates kızartması ile servis edilir', price: '₺520', calories: '840' },
      { key: 'hookah_pub_burger', name: 'Hookah Pub Burger', desc: '120 gr dana köfte üzerine 120 gr bonfilenin mantar ve kırmızı biberle buluşması, patates kızartması ile servis edilir', price: '₺545', calories: '980' },
    ],
  },
  {
    id: 'pizzas',
    category: 'Pizzas',
    items: [
      { key: 'bonfile_pizza', name: 'Yaprak Bonfile Pizza', desc: 'Yaprak bonfile, kırmızı biber, mozerella, özel kekik sos, roka', price: '₺500', calories: '850' },
      { key: 'mixed_pizza', name: 'Karışık Pizza', desc: 'Dana sucuk, dana salam, dana sosis, siyah zeytin, mantar, biber, mozerella', price: '₺460', calories: '920' },
      { key: 'margarita_pizza', name: 'Margarita Pizza', desc: 'Mozerella, domates ve özel sos', price: '₺425', calories: '740' },
      { key: 'sucuk_pizza', name: 'Dana Sucuk Pizza', desc: 'Dana sucuk, mozerella, siyah zeytin, yeşil biber', price: '₺445', calories: '880' },
      { key: 'sosis_pizza', name: 'Dana Sosis Pizza', desc: 'Dana sosis, mozerella, siyah zeytin, yeşil biber', price: '₺445', calories: '860' },
      { key: 'sucuk_sosis_pizza', name: 'Dana Sucuk Sosis Pizza', desc: 'Dana sucuk, dana sosis, mozerella, siyah zeytin, yeşil biber', price: '₺445', calories: '940' },
      { key: 'vegetarian_pizza', name: 'Vejeteryan Pizza', desc: 'Mozerella, mantar, domates, yeşil zeytin, siyah zeytin, roka', price: '₺425', calories: '690' },
    ],
  },
  {
    id: 'chicken',
    category: 'Chicken',
    items: [
      { key: 'curry_chicken', name: 'Köri Soslu Tavuk', desc: '200 gr tavuk, özel krema sosumuz ile mantarın buluşması', price: '₺420', calories: '480' },
      { key: 'hookah_special_chicken', name: 'Hookah Special Tavuk', desc: '200 gr tavuğun şefin mantar, krema, fesleğen ile buluştuğu lezzet', price: '₺440', calories: '520' },
      { key: 'soy_chicken', name: 'Soya Soslu Tavuk', desc: '200 gr tavuk, soya sosu, mantar ve krema', price: '₺420', calories: '410' },
      { key: 'grilled_chicken', name: 'Tavuk Izgara', desc: '200 gr tavuk, domates, salatalık, yeşillik ve pilav', price: '₺420', calories: '540' },
      { key: 'schnitzel', name: 'Şinitzel', desc: '', price: '₺420', calories: '580' },
    ],
  },
  {
    id: 'meatballs',
    category: 'Meatballs',
    items: [
      { key: 'butcher_kofte', name: 'Kasap Köfte', desc: '', price: '₺440', calories: '460' },
      { key: 'kasarli_kofte', name: 'Kaşarlı Kasap Köfte', desc: '', price: '₺460', calories: '580' },
      { key: 'yogurt_sauce_kofte', name: 'Yoğurtlu Soslu Köfte', desc: '', price: '₺500', calories: '590' },
      { key: 'yogurt_bonfile', name: 'Özel Yoğurtlu Soslu Yaprak Bonfile', desc: '', price: '₺530', calories: '640' },
      { key: 'inegol_kofte', name: 'İnegöl Köfte', desc: '', price: '₺460', calories: '' },
      { key: 'kofte_ekmek', name: 'Köfte Ekmek', desc: '', price: '₺430', calories: '' },
    ],
  },
  {
    id: 'hot_starters',
    category: 'Hot Starters',
    items: [
      { key: 'french_fries', name: 'Patates Kızartması', desc: 'İsteğinize göre baharatlı olarak servis edilir', price: '₺300', calories: '380' },
      { key: 'crispy_chicken_basket', name: 'Çıtır Tavuk Sepeti', desc: 'Özel soslu çıtır tavuk, patates kızartması', price: '₺400', calories: '650' },
      { key: 'sausage_basket', name: 'Sosis Tava Sepeti', desc: 'Dana sosis, patates kızartması', price: '₺400', calories: '620' },
      { key: 'mixed_hot_basket', name: 'Karışık Sıcak Sepeti', desc: 'Patates, paçanga böreği, soğan halkası, sigara böreği, çıtır tavuk, sosis', price: '₺480', calories: '780' },
      { key: 'cheddar_fries', name: 'Cheddarlı Patates', desc: 'Özel cheddar soslu patates kızartması', price: '₺330', calories: '540' },
    ],
  },
  {
    id: 'pasta',
    category: 'Pasta',
    items: [
      { key: 'spaghetti_bolognese', name: 'Spaghetti Bolonez', desc: 'Dana kıyma, özel sos ile birleşen harika tat', price: '₺360', calories: '590' },
      { key: 'penne_alfredo', name: 'Penne Alfredo', desc: 'Dana bonfile, mantar, krema sos ile', price: '₺410', calories: '740' },
      { key: 'napolitane', name: 'Napoliten', desc: '', price: '₺340', calories: '430' },
      { key: 'chicken_penne', name: 'Chicken Penne', desc: '', price: '₺380', calories: '610' },
      { key: 'homemade_manti', name: 'Ev Yapımı Mantı', desc: '', price: '₺340', calories: '520' },
      { key: 'chicken_curry_penne', name: 'Chicken Korisos Penne', desc: 'Tavuk köri sos ile', price: '₺380', calories: '660' },
    ],
  },
  {
    id: 'nuts',
    category: 'Nuts & Fruit',
    items: [
      { key: 'nuts_plate', name: 'Çerez Tabağı', desc: '', price: '₺270', calories: '580' },
      { key: 'pistachios', name: 'Antep Fıstığı', desc: '', price: '', calories: '' },
      { key: 'peanuts', name: 'Fıstık', desc: '', price: '₺170', calories: '560' },
      { key: 'fruit_plate', name: 'Meyve Tabağı', desc: '', price: '₺400', calories: '220' },
    ],
  },
  {
    id: 'desserts',
    category: 'Desserts',
    items: [
      { key: 'lemon_cheesecake', name: 'Cheesecake Limonlu Mono', desc: 'Cheesecake Bisküvi Tabanı, Cheesecake Peynir Kreması, Limonlu Kremalı Sos', price: '₺320', calories: '410' },
      { key: 'souffle', name: 'Sufle', desc: 'Akışkan Çikolatalı Kek', price: '₺320', calories: '' },
      { key: 'white_cascada', name: 'White Cascada', desc: 'Bitter Çikolatalı, Böğürtlen ve Akışkan Çikolata Soslu, Üzeri Beyaz Çikolata ve Antep Fıstığı Kaplamalı', price: '₺320', calories: '' },
      { key: 'aligo', name: 'Aligo', desc: "Tart Hamuru Tabanlı, İçi Devil's Kek, Karamel Sos, Üzeri Fındık Kaplamalı", price: '₺320', calories: '' },
      { key: 'tiramisu', name: 'Tiramisu', desc: 'Kahveli Kakaolu Pandispanya Kek, Peynirli Krema', price: '₺320', calories: '' },
    ],
  },
]

export const NON_ALCOHOLIC_DRINKS = [
  {
    id: 'non_alcoholic_cocktails',
    category: 'Non-Alcoholic Cocktails',
    items: [
      { key: 'sunrise_sunset', name: 'Sunrise Sunset', desc: 'Karadut püresi, sarı Red Bull, buz', price: '' },
      { key: 'skys_the_limit', name: "Sky's the Limit", desc: 'Karadut püresi, beyaz Red Bull, buz', price: '' },
      { key: 'one_in_a_melon', name: 'One in a Melon', desc: 'Çilek püresi, mango püresi, Red Bull Red, buz', price: '' },
      { key: 'starry_eyed', name: 'Starry Eyed', desc: 'Karadut püresi, karadut şurubu, narenciye şurubu, Red Bull Blue, buz', price: '' },
    ],
  },
  {
    id: 'herbal_teas',
    category: 'Herbal Teas',
    items: [
      { key: 'linden', name: 'Ihlamur', desc: '', price: '₺200' },
      { key: 'sage', name: 'Adaçayı', desc: '', price: '₺200' },
      { key: 'cinnamon_apple_tea', name: 'Tarçınlı Elma Çayı', desc: '', price: '₺200' },
      { key: 'winter_tea', name: 'Kış Çayı', desc: '', price: '₺200' },
      { key: 'mixed_herbal', name: 'Karışık Bitki Çayı', desc: '', price: '₺200' },
      { key: 'green_tea', name: 'Yeşil Çay', desc: '', price: '₺200' },
      { key: 'rosehip', name: 'Kuşburnu', desc: '', price: '₺200' },
    ],
  },
  {
    id: 'teas',
    category: 'Teas',
    items: [
      { key: 'brewed_tea', name: 'Demleme Çay', desc: '', price: '₺70' },
      { key: 'cup_tea', name: 'Fincan Çay', desc: '', price: '₺110' },
      { key: 'milk', name: 'Süt', desc: '', price: '₺90' },
      { key: 'honey_milk', name: 'Ballı Süt', desc: '', price: '₺100' },
    ],
  },
  {
    id: 'sahlep',
    category: 'Sahlep',
    items: [
      { key: 'sahlep', name: 'Sahlep', desc: '', price: '₺200' },
      { key: 'mastiha_sahlep', name: 'Sakızlı Sahlep', desc: '', price: '₺200' },
      { key: 'mastiha_hazelnut_sahlep', name: 'Sakız Fındık Parçalı Sahlep', desc: '', price: '₺200' },
      { key: 'pistachio_sahlep', name: 'Antep Fıstıklı Sahlep', desc: '', price: '₺200' },
    ],
  },
  {
    id: 'cold_drinks',
    category: 'Cold Drinks',
    items: [
      { key: 'lemonade', name: 'Limonata', desc: '', price: '₺190' },
      { key: 'ice_tea', name: 'Ice Tea', desc: '', price: '₺130' },
      { key: 'cola', name: 'Cola', desc: '', price: '₺120' },
      { key: 'cola_zero', name: 'Cola Zero', desc: '', price: '₺120' },
      { key: 'fanta', name: 'Fanta', desc: '', price: '₺120' },
      { key: 'sprite', name: 'Sprite', desc: '', price: '₺130' },
      { key: 'red_bull', name: 'Red Bull', desc: '', price: '₺200' },
      { key: 'ayran', name: 'Ayran', desc: '', price: '₺100' },
      { key: 'fruit_juices', name: 'Meyve Suları', desc: '', price: '₺120' },
      { key: 'soda', name: 'Soda', desc: '', price: '₺80' },
      { key: 'glass_water', name: 'Cam Su', desc: '', price: '₺70' },
      { key: 'fruit_soda', name: 'Meyveli Soda', desc: '', price: '₺85' },
      { key: 'churchill', name: 'Churchill', desc: '', price: '₺120' },
    ],
  },
  {
    id: 'special_coffees',
    category: 'Special Coffees',
    items: [
      { key: 'coffee_latte', name: 'Coffee Latte', desc: '', price: '₺200' },
      { key: 'caramel_latte', name: 'Caramel Latte', desc: '', price: '₺200' },
      { key: 'coconut_latte', name: 'Coconut Latte', desc: '', price: '₺200' },
      { key: 'white_choc_latte', name: 'White Chocolate Latte', desc: '', price: '₺200' },
      { key: 'hazelnut_latte', name: 'Hazelnut Latte', desc: '', price: '₺200' },
      { key: 'vanilla_latte', name: 'Vanilya Latte', desc: '', price: '₺200' },
      { key: 'cappuccino', name: 'Cappuccino', desc: '', price: '₺200' },
      { key: 'mocha', name: 'Mocha', desc: '', price: '₺200' },
      { key: 'white_mocha', name: 'White Mocha', desc: '', price: '₺200' },
      { key: 'espresso', name: 'Espresso', desc: '', price: '₺170' },
      { key: 'double_espresso', name: 'Double Espresso', desc: '', price: '₺200' },
      { key: 'americano', name: 'Americano', desc: '', price: '₺200' },
      { key: 'filter_coffee', name: 'Filtre Kahve', desc: '', price: '₺200' },
      { key: 'latte_macchiato', name: 'Latte Macchiato', desc: '', price: '₺200' },
      { key: 'milk_nescafe', name: 'Sütlü Nescafe', desc: '', price: '₺200' },
      { key: 'plain_nescafe', name: 'Sade Nescafe', desc: '', price: '₺200' },
    ],
  },
  {
    id: 'cold_coffees',
    category: 'Cold Coffees',
    items: [
      { key: 'iced_mocha', name: 'Iced Mocha', desc: '', price: '₺220' },
      { key: 'iced_latte', name: 'Iced Latte', desc: '', price: '₺220' },
      { key: 'iced_white_choc_latte', name: 'Iced White Chocolate Latte', desc: '', price: '₺220' },
      { key: 'iced_hazelnut_latte', name: 'Iced Hazelnut Latte', desc: '', price: '₺220' },
      { key: 'iced_caramel_latte', name: 'Iced Caramel Latte', desc: '', price: '₺220' },
      { key: 'iced_vanilla_latte', name: 'Iced Vanilla Latte', desc: '', price: '₺220' },
      { key: 'iced_americano', name: 'Iced Americano', desc: '', price: '₺220' },
    ],
  },
  {
    id: 'turkish_coffees',
    category: 'Turkish Coffees',
    items: [
      { key: 'turkish_coffee', name: 'Türk Kahvesi', desc: '', price: '₺140' },
      { key: 'choc_hazelnut_turkish', name: 'Çikolatalı Fındıklı Türk Kahvesi', desc: '', price: '₺140' },
      { key: 'mastiha_turkish', name: 'Damla Sakızlı Türk Kahvesi', desc: '', price: '₺140' },
      { key: 'choc_turkish', name: 'Çikolatalı Türk Kahvesi', desc: '', price: '₺140' },
      { key: 'menengi_coffee', name: 'Menengiç Kahvesi', desc: '', price: '₺140' },
      { key: 'ottoman_dibek', name: 'Osmanlı Dibek Kahvesi', desc: '', price: '₺140' },
    ],
  },
  {
    id: 'hot_chocolate',
    category: 'Hot Chocolate',
    items: [
      { key: 'hot_chocolate', name: 'Hot Chocolate', desc: '', price: '₺200' },
      { key: 'white_caramel_choc', name: 'White Caramel Chocolate', desc: '', price: '₺200' },
      { key: 'white_hot_choc', name: 'White Hot Chocolate', desc: '', price: '₺200' },
      { key: 'vanilla_bean_hot_choc', name: 'Vanilla Bean Hot Chocolate', desc: '', price: '₺200' },
      { key: 'vanilla_bean_white', name: 'Vanilla Bean White', desc: '', price: '₺200' },
    ],
  },
  {
    id: 'cold_chocolate',
    category: 'Cold Chocolate',
    items: [
      { key: 'iced_chocolate', name: 'Iced Chocolate', desc: '', price: '₺220' },
      { key: 'iced_white_choc', name: 'Iced White Chocolate', desc: '', price: '₺220' },
      { key: 'iced_caramel_choc', name: 'Iced Caramel Chocolate', desc: '', price: '₺220' },
      { key: 'iced_vanilla_choc', name: 'Iced Vanilla Chocolate', desc: '', price: '₺220' },
      { key: 'iced_hazelnut_choc', name: 'Iced Hazelnut Chocolate', desc: '', price: '₺220' },
    ],
  },
  {
    id: 'frozen',
    category: 'Natural Frozen',
    items: [
      { key: 'frozen_mango', name: 'Mango', desc: '', price: '₺220' },
      { key: 'frozen_mixed_berry', name: 'Mixed Berry', desc: '', price: '₺220' },
      { key: 'frozen_mulberry', name: 'Karadut', desc: '', price: '₺220' },
      { key: 'frozen_melon', name: 'Kavun', desc: '', price: '₺220' },
      { key: 'frozen_peach', name: 'Şeftali', desc: '', price: '₺220' },
      { key: 'frozen_passion', name: 'Passion Fruit', desc: '', price: '₺220' },
      { key: 'frozen_green_apple', name: 'Yeşil Elma', desc: '', price: '₺220' },
      { key: 'frozen_mango_pineapple', name: 'Mango Ananas', desc: '', price: '₺220' },
      { key: 'frozen_strawberry_lemonade', name: 'Strawberry Lemonade', desc: '', price: '₺220' },
    ],
  },
  {
    id: 'smoothies',
    category: 'Smoothies',
    items: [
      { key: 'mango_cream', name: 'Mango Cream', desc: '', price: '₺220' },
      { key: 'mulberry_cream', name: 'Black Mulberry Cream', desc: '', price: '₺220' },
      { key: 'strawberry_cream', name: 'Strawberry Cream', desc: '', price: '₺220' },
      { key: 'peaches_cream', name: 'Peaches Cream', desc: '', price: '₺220' },
      { key: 'banana_cream', name: 'Banana Cream', desc: '', price: '₺220' },
      { key: 'melon_cream', name: 'Melon Cream', desc: '', price: '₺220' },
      { key: 'coconut_cream', name: 'Coconut Cream', desc: '', price: '₺220' },
      { key: 'banana_honey_milk', name: 'Muzlu Ballı Süt', desc: '', price: '₺220' },
    ],
  },
]

export const ALCOHOLIC_DRINKS = [
  {
    id: 'kampanya',
    category: 'Kampanya',
    items: [
      { key: 'tuborg_5li', name: '5\'li Tuborg', desc: '5 adet Tuborg 50cl', price: '₺1.000' },
      { key: 'carlsberg_5li', name: '5\'li Carlsberg', desc: '5 adet Carlsberg 50cl', price: '₺1.000' },
    ],
  },
  {
    id: 'cocktails',
    category: 'Cocktails',
    items: [
      { key: 'margarita', name: 'Margarita', desc: 'Tequila, limon suyu, tuz, portakal likörü', price: '₺550' },
      { key: 'blue_hawaii', name: 'Blue Hawaii', desc: 'Vodka, rom, ananas suyu, blue curacao likörü', price: '₺550' },
      { key: 'long_island', name: 'Long Island Iced Tea', desc: 'Vodka, tequila, rom, cin, portakal likörü, cola', price: '₺550' },
      { key: 'tequila_sunrise', name: 'Tequila Sunrise', desc: 'Tequila, portakal suyu, nar şurubu', price: '₺550' },
      { key: 'cosmopolitan', name: 'Cosmopolitan', desc: 'Vodka, portakal likörü, limon suyu, kızılcık suyu', price: '₺550' },
      { key: 'mojito', name: 'Mojito', desc: 'Rom, esmer şeker, taze nane, misket limon, soda', price: '₺530' },
      { key: 'lynchburg_lemonade', name: 'Lynchburg Lemonade', desc: 'Jack Daniels, portakal likörü, limonata, sprite', price: '₺550' },
      { key: 'bramble', name: 'Bramble', desc: 'Cin, limon suyu, böğürtlen likörü', price: '₺550' },
      { key: 'tropicana', name: 'Tropicana', desc: 'Rum, malibu, passion fruit, mango, ananas suyu, lime suyu', price: '₺550' },
      { key: 'green_face', name: 'Green Face', desc: 'Vodka, cin, archers, yeşil elma suyu, limon suyu', price: '₺560' },
      { key: 'cuba_libre', name: 'Cuba Libre', desc: 'Rom, kola, limon suyu', price: '₺550' },
      { key: 'sex_on_beach', name: 'Sex on the Beach', desc: 'Vodka, archers, portakal suyu, nar şurubu', price: '₺560' },
      { key: 'kingpin', name: 'Kingpin', desc: 'Vodka, archers, limonata, nar şurubu', price: '₺560' },
      { key: 'jager_boom', name: 'Jager Boom', desc: 'Jagermeister, redbull', price: '₺530' },
    ],
  },
  {
    id: 'aperitifs',
    category: 'Aperitifs',
    items: [
      { key: 'aperol_spritz', name: 'Aperol Spritz', desc: 'Aperol, Prosecco, Soda', price: '₺450' },
      { key: 'campari_negroni', name: 'Campari Negroni', desc: 'Campari, Cin, Kırmızı Vermut', price: '₺450' },
      { key: 'campari_spritz', name: 'Campari Spritz', desc: 'Campari, Prosecco, Soda', price: '₺450' },
      { key: 'campari_americano', name: 'Campari Americano', desc: 'Campari, Kırmızı Vermut, Soda', price: '₺450' },
      { key: 'campari_tonic', name: 'Campari Tonic', desc: 'Campari, Tonik', price: '₺450' },
    ],
  },
  {
    id: 'wines',
    category: 'Wines',
    items: [
      { key: 'terra_red', name: 'Terra Öküzgözü Boğazkere', desc: '', price: '₺400' },
      { key: 'buzdagi', name: 'Buzdağ', desc: '', price: '₺400' },
      { key: 'cielo_pinot_grigio', name: 'Cielo Pinot Grigio', desc: '', price: '₺400' },
      { key: 'cielo_merlot', name: 'Cielo Merlot', desc: '', price: '₺400' },
      { key: 'leona_blush', name: 'Leona Blush', desc: '', price: '₺400' },
    ],
  },
  {
    id: 'import_spirits',
    category: 'Import Spirits',
    items: [
      { key: 'absolut_vodka', name: 'Absolut Vodka', desc: '', price: '₺450' },
      { key: 'olmeca_tequila', name: 'Olmeca Tequila', desc: '', price: '' },
      { key: 'beefeater_gin', name: 'Beefeater Gin', desc: '', price: '₺450' },
      { key: 'tanqueray_gin', name: 'Tanqueray Gin', desc: '', price: '' },
      { key: 'baileys', name: 'Baileys', desc: '', price: '₺400' },
      { key: 'malibu', name: 'Malibu', desc: '', price: '₺400' },
      { key: 'jagermeister', name: 'Jagermeister', desc: '', price: '₺260' },
    ],
  },
  {
    id: 'whiskeys',
    category: 'Whiskies',
    items: [
      { key: 'chivas_12', name: 'Chivas Regal (12 Y)', desc: '', price: '₺475' },
      { key: 'chivas_18', name: 'Chivas Regal (18 Y)', desc: '', price: '' },
      { key: 'jack_daniels', name: 'Jack Daniels No.7', desc: '', price: '₺475' },
      { key: 'jameson', name: 'Jameson', desc: '', price: '₺425' },
      { key: 'chivas_35cl', name: 'Chivas Regal 35 cl', desc: '', price: '₺2.500' },
      { key: 'chivas_70cl', name: 'Chivas Regal 70 cl', desc: '', price: '₺4.000' },
      { key: 'jack_70cl', name: 'Jack Daniels 70 cl', desc: '', price: '₺4.000' },
      { key: 'jameson_70cl', name: 'Jameson 70 cl', desc: '', price: '₺3.500' },
    ],
  },
  {
    id: 'raki',
    category: 'Raki',
    items: [
      { key: 'tekirdag_tek', name: 'Tekirdağ Gold — Tek', desc: '', price: '₺400' },
      { key: 'tekirdag_duble', name: 'Tekirdağ Gold — Duble', desc: '', price: '₺650' },
      { key: 'tekirdag_20cl', name: 'Tekirdağ Gold — 20 cl', desc: '', price: '₺1.100' },
      { key: 'tekirdag_35cl', name: 'Tekirdağ Gold — 35 cl', desc: '', price: '₺1.700' },
      { key: 'tekirdag_70cl', name: 'Tekirdağ Gold — 70 cl', desc: '', price: '₺3.000' },
    ],
  },
  {
    id: 'beers',
    category: 'Bottled Beers',
    items: [
      { key: 'tuborg_gold_33', name: 'Tuborg Gold 33cl', desc: '', price: '₺200' },
      { key: 'tuborg_50', name: 'Tuborg 50cl', desc: '', price: '₺215' },
      { key: 'tuborg_filtresiz_50', name: 'Tuborg Filtresiz 50cl', desc: '', price: '₺220' },
      { key: 'tuborg_amber_50', name: 'Tuborg Amber 50cl', desc: '', price: '₺220' },
      { key: 'tuborg_special_50', name: 'Tuborg Special 50cl Kutu', desc: '', price: '₺265' },
      { key: 'carlsberg_33', name: 'Carlsberg 33cl', desc: '', price: '₺205' },
      { key: 'carlsberg_50', name: 'Carlsberg 50cl', desc: '', price: '₺220' },
      { key: 'carlsberg_luna_50', name: 'Carlsberg Luna 50cl', desc: '', price: '₺220' },
      { key: 'blanc_33', name: 'Blanc 33cl', desc: '', price: '₺215' },
      { key: 'frederik_ipa', name: 'Frederik India Pale Ale 35cl', desc: '', price: '₺255' },
      { key: 'frederik_yakima', name: 'Frederik Yakima IPA 35cl', desc: '', price: '₺255' },
      { key: 'frederik_wheat', name: 'Frederik Wheat IPA 35cl', desc: '', price: '₺255' },
      { key: 'frederik_marzen', name: 'Frederik Märzen Lager 35cl', desc: '', price: '₺255' },
      { key: 'frederik_brown', name: 'Frederik Brown Ale 35cl', desc: '', price: '₺255' },
      { key: 'sol_33', name: 'Sol Cerveza 33cl', desc: '', price: '₺275' },
      { key: 'desperados_33', name: 'Desperados 33cl', desc: '', price: '₺290' },
      { key: 'weihenstephan_33', name: 'Weihenstephan Hefeweissbier 33cl', desc: '', price: '₺275' },
      { key: 'weihenstephan_vitus', name: 'Weihenstephan Vitus 33cl', desc: '', price: '₺290' },
      { key: 'guinness_44', name: 'Guinness 44cl Kutu', desc: '', price: '₺315' },
    ],
  },
]
